name: JIRA Connection
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  enforce-issue:
    runs-on: ubuntu-latest
    name: JIRA Association
    steps:
      - uses: actions/checkout@v6
      - name: Check for JIRA ISSUE
        id: check
        uses: ./
        with:
          ignore-author: dependabot[bot],supplypiker
          project: 'SRENEW'
          jira-host: ${{ secrets.JIRA_HOST }}
          jira-email: ${{ secrets.JIRA_EMAIL }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
